
# psutil.cpu_percent(interval=1, percpu=False)
- method: 'cpu_percent'
  params:
    - 'interval': 1
    - 'percpu': False

# psutil.swap_memory().percent:
- method: 'swap_memory'
  select: 'percent'